### PR TITLE
Fix integration test errors in the modification to fix #512

### LINKED ISSUE #512: BAR file 90_rootprops.xml should not use a "personium-localunit:" URL.
## Error  
Latest release that supports "personium-localunit:" literrals fail when installing BAR file.

BarImportError

## Error message from Unit Manager  
```
{
    "schema": "https://app-myboard.appdev.personium.io/",
    "name": "appdev",
    "started_at": "2019-11-06T07:05:14.959Z",
    "progress": "66%",
    "message": {
        "code": "PL-BI-1004",
        "message": {
            "lang": "en",
            "value": "Installation failed([90_rootprops.xml] file format error.)."
        }
    },
    "url": "https://dixonsiu.appdev.personium.io/appdev/",
    "status": "installation failed"
}
```
## Expected behaviour  
acl tag should allow new format of URL.

### PR DESCRIPTION
**Pull request by shimono**

### CODE REVIEW

File: src/main/java/io/personium/core/model/jaxb/ObjectIo.java [hunk 1]
```diff
@@ -63,7 +65,8 @@ private ObjectIo() {
             jsonContext = JAXBContextFactory.createContext(ObjectIo.class.getPackage().getName(),
                     ObjectIo.class.getClassLoader());
             nameSpaceToJsonMap.put("DAV:", "D");
-            nameSpaceToJsonMap.put("p:", "p");
+            //nameSpaceToJsonMap.put("p:", "p");
+            nameSpaceToJsonMap.put(CommonUtils.XmlConst.NS_PERSONIUM, CommonUtils.XmlConst.NS_PREFIX_PERSONIUM);
```
Comment (shimono) [inline src/main/java/io/personium/core/model/jaxb/ObjectIo.java]: This change causes the ACL data incompatibility. 
now the requireSchemaAuthz info is stored with key:
New Key; "@p.requireSchemaAuthz" 
instead of 
Ole Key: "@requireSchemaAuthz"

File: src/main/java/io/personium/core/model/jaxb/Acl.java [hunk 2]
```diff
@@ -156,7 +156,12 @@ public static Acl fromJson(final String jsonString) {
             //  attr somehow not unmarshalled so manually fix the object
             JSONParser parser = new JSONParser();
             JSONObject j = (JSONObject) parser.parse(jsonString);
-            ret.setRequireSchemaAuthz((String) j.get(KEY_REQUIRE_SCHEMA_AUTHZ));
+            // -- TODO Delete this block after 1.8.x
+            // backward compatibility for json data before 1.7.20
+            if (ret.requireSchemaAuthz == null) {
+                ret.setRequireSchemaAuthz((String) j.get(KEY_LEGACY_REQUIRE_SCHEMA_AUTHZ));
```
Comment (shimono) [inline src/main/java/io/personium/core/model/jaxb/Acl.java]: (*) this is necessary because the requireSchemaAuthz attribute in the ACL will be stored with a new key.

-  New Key:  "@p.requireSchemaAuthz"
-  Old Key:  "@requireSchemaAuthz"

**Comment by shimono** [comment]
Merging this to check if the develop branch error will be fixed or not
