### PR TITLE
Fix #501, #500, #503 = #506

### LINKED ISSUE #501: Role info lost in tokens via grant code flow after v1.7.18
## Bug Overview

When grant_code is used at token endpoint to issue an access token, the token subject does not have the association with the roles that should be allocated to it.

## How it was found 

Calling Retrieve Box Meta Data API failed in v1.7.18 later

### Related:
- personium/app-timefiller#40
- personium/app-personium-calendar#155
- #500

### PR DESCRIPTION
**Pull request by shimono**
### 501 Bug analysis

It was a degrade from 1.7.18.

When grant_code is used at token endpoint to issue an access token, the token subject does not have the association with the roles that should be allocated to it.

### Causes of the degrade :
  - Appropriate tests were missing 
  - At 1.7.18, a refactoring was performed against confused codes around Tokens, especially grant code.

### This PR includes
  - fix for the bug 501
  - Scenario test that simulates the app launching flow from the current HomeApp.
  - fix for 503 = #506

### CODE REVIEW

File: src/test/java/io/personium/core/auth/AccessContextTest.java [hunk 1]
```diff
@@ -147,29 +164,34 @@ public void testCreate() {
...
     }
 
-    /**
-     * testCreateBasicのテスト.
-     * TODO V1.1 Basic認証に対応後有効化する
-     */
     @Test
-    @Ignore
-    public void testCreateBasic() {
+    public void create_Basic_Valid_ShouldReturn_TypeBasic() {
```
Comment (shimono) [inline src/test/java/io/personium/core/auth/AccessContextTest.java]: Fixed a broken test

File: src/test/java/io/personium/core/auth/AccessContextTest.java [hunk 2]
```diff
@@ -147,29 +164,34 @@ public void testCreate() {
...
+    		null
+        );
+        when(cell.getAccount(Matchers.anyString())).thenReturn(oew);
         when(cell.authenticateAccount((OEntityWrapper) Matchers.any(), Matchers.anyString())).thenReturn(true);
         // 第1引数は AuthHeader, 第2引数は UriInfo, 第3引数は cookie_peer, 第4引数は cookie内の暗号化されたトークン情報
         AccessContext accessContext = AccessContext.create(auth,
                 null, null, null, cell, BASE_URL, UrlUtils.getHost(), OWNER);
-        assertEquals(accessContext.getType(), AccessContext.TYPE_BASIC);
-
+        assertEquals(AccessContext.TYPE_BASIC, accessContext.getType());
```
Comment (shimono) [inline src/test/java/io/personium/core/auth/AccessContextTest.java]: param order should be expected, actual.
(was inverse)

File: src/test/java/io/personium/core/auth/AccessContextTest.java [hunk 3]
```diff
@@ -37,23 +42,28 @@
...
 import io.personium.core.odata.OEntityWrapper;
+import io.personium.core.rs.PersoniumCoreApplication;
 import io.personium.test.categories.Unit;
-import io.personium.test.jersey.PersoniumIntegTestRunner;
 import io.personium.test.unit.core.UrlUtils;
 
 /**
  * Unit test class for AccessContext.
  */
-@RunWith(PersoniumIntegTestRunner.class)
```
Comment (shimono) [inline src/test/java/io/personium/core/auth/AccessContextTest.java]: This is a unit test, not Integration test.

File: src/test/java/io/personium/core/auth/AccessContextTest.java [hunk 4]
```diff
@@ -74,9 +84,17 @@
...
+     * @throws CertificateException 
+     * @throws InvalidKeySpecException 
+     * @throws Exception 
      */
     @BeforeClass
-    public static void beforeClass() {
+    public static void beforeClass() throws Exception {
+        PersoniumCoreApplication.loadConfig();
+        TransCellAccessToken.configureX509(PersoniumUnitConfig.getX509PrivateKey(),
+                PersoniumUnitConfig.getX509Certificate(), PersoniumUnitConfig.getX509RootCertificate());
```
Comment (shimono) [inline src/test/java/io/personium/core/auth/AccessContextTest.java]: We need these initialization lines since this part used to be handled by the IntegTestRunner.

File: src/test/java/io/personium/core/auth/AccessContextTest.java [hunk 5]
```diff
@@ -134,10 +152,9 @@ public void testGetRoleList() {
     }
 
     /**
-     * testCreateBasicのテスト.
      */
     @Test
-    public void testCreate() {
+    public void create_NoAuthzHeader_ShouldReturn_TypeAnonymous() {
```
Comment (shimono) [inline src/test/java/io/personium/core/auth/AccessContextTest.java]: test name improvement.

```
{targetMethodName}_{Condition}_{Result}
```

I know in JUnit culture, people use the following method name convention.

```
test{targetMethodName}
```

The "test" part is obvious since it is a Test Class, and the we usually have input / result variations.

File: src/test/java/io/personium/core/auth/AccessContextTest.java [hunk 6]
```diff
@@ -360,6 +382,23 @@ public void testCreateBearerAuthzCellNullParamBearerSpace() {
...
+        
+        Box box = new Box(cell, "box", schema, "abcde", new Date().getTime()-1000000);
+
+        List<Role> roleList = new ArrayList<>();
+        VisitorLocalAccessToken vlat = new VisitorLocalAccessToken(new Date().getTime(), 3600, cell.getUrl(), "https://user1.unit.example/#me",
+        		roleList, schema + OAuth2Helper.Key.CONFIDENTIAL_MARKER, new String[] {"root"});
+        String authzHeaderValue = "Bearer " + vlat.toTokenString();
+        AccessContext ac = AccessContext.create(authzHeaderValue, new TestUriInfo(), null, null, cell, BASE_URL, UrlUtils.getHost(), null);
+        ac.checkSchemaMatches(box);
+    }
```
Comment (shimono) [inline src/test/java/io/personium/core/auth/AccessContextTest.java]: New test to test #503=#506

File: src/test/java/io/personium/core/rs/cell/TokenEndPointResourceTest.java [hunk 7]
```diff
@@ -79,26 +77,26 @@
 import io.personium.test.categories.Unit;
 
 /**
- * TokenEndPointResource unit test classs.
+ * TokenEndPointResource unit test class.
  */
-@RunWith(PowerMockRunner.class)
```
Comment (shimono) [inline src/test/java/io/personium/core/rs/cell/TokenEndPointResourceTest.java]: With PowerMockRunner, we can not somehow handle TransCellAccessToken.

Comment (shimono) [reply src/test/java/io/personium/core/rs/cell/TokenEndPointResourceTest.java]: This test was using PowerMock excessively, so changed the whole test to minimize the use of Mocks

File: src/test/java/io/personium/core/rs/cell/TokenEndPointResourceTest.java [hunk 8]
```diff
@@ -79,26 +77,26 @@
...
     private CellRsCmp mockCellRsCmp;
     private UriInfo mockUriInfo;
+    private String xForwadedFor = "1.2.3.4";
 
     @BeforeClass
-    public static void beforeClass() {
+    public static void beforeClass() throws Exception {
         PersoniumCoreApplication.loadConfig();
+        TransCellAccessToken.configureX509(PersoniumUnitConfig.getX509PrivateKey(),
+                PersoniumUnitConfig.getX509Certificate(), PersoniumUnitConfig.getX509RootCertificate());
```
Comment (shimono) [inline src/test/java/io/personium/core/rs/cell/TokenEndPointResourceTest.java]: Necessary initialization (loading X509 files) for using TransCellAccessToke class in the tests.

File: src/test/java/io/personium/core/rs/cell/TokenEndPointResourceTest.java [hunk 9]
```diff
@@ -196,58 +192,27 @@ public EdmEntityType getEntityType() {
...
     /**
-     * Test receiveRefresh().
-     * RefreshToken is CellLocalToken.
+     * Test receiveRefresh() using ResidentRefreshToken.
      * @throws Exception Unexpected error.
      */
-    @SuppressWarnings("unchecked")
     @Test
-    public void receiveRefresh_Normal_cell_local_token() throws Exception {
+    public void receiveRefresh_ResidentRefreshToken_When_Valid_Succeeds() throws Exception {
```
Comment (shimono) [inline src/test/java/io/personium/core/rs/cell/TokenEndPointResourceTest.java]: Method name changes
```
{targetMethodName}_{Conditions}_{result}
```

File: src/test/java/io/personium/core/rs/cell/TokenEndPointResourceTest.java [hunk 10]
```diff
@@ -422,10 +449,72 @@ public void testToken_nullClientAssertionTypeAndValidClientAssertion_shouldFail(
...
             tokenEndPointResource.token(this.mockUriInfo, null, formParams, xForwadedFor);
+            fail("Should throw exception");
         } catch (PersoniumCoreAuthnException e) {
             assertEquals(PersoniumCoreAuthnException.INVALID_CLIENT_ASSERTION_TYPE.getCode(), e.getCode());
-            return;
         }
-        fail("Should throw exception");
+    }
+    
+    @Test
```
Comment (shimono) [inline src/test/java/io/personium/core/rs/cell/TokenEndPointResourceTest.java]: Added tests for "grant_code"

File: src/test/java/io/personium/test/jersey/cell/auth/AuthAccountStatusTest.java [hunk 11]
```diff
@@ -128,9 +128,9 @@ public final void test_handlePassword() {
         String url = (String) responseBody.get("url");
         String lastAuthenticated = (String) responseBody.get("last_authenticated");
         Long failedCount = (Long) responseBody.get("failed_count");
-        assertThat(error, is(OAuth2Helper.Error.UNAUTHORIZED_CLIENT));
+        assertThat(error, is(OAuth2Helper.Error.INVALID_GRANT));
```
Comment (shimono) [inline src/test/java/io/personium/test/jersey/cell/auth/AuthAccountStatusTest.java]: Changed the error reason.
When password needs change, the client does not have any fault,
rather we could interpret like user's grant is not sufficient.

File: src/test/java/io/personium/test/jersey/scenario/HomeAppScenarioTest.java [hunk 12]
```diff
@@ -0,0 +1,315 @@
...
+     *  -  access token issued from token endpoint of user cell.
+     *  - BoxDiscovery
+     *  - GET BoxMetadata
+     */
+    @Test
+    public final void ROPCLogin_SetCookie_AppLaunch_FromCookieToGrantCode_BoxDiscovery_BoxMetadata()
+            throws ClientProtocolException, IOException, TokenParseException {
+        //ROPC at Test Cell1 By Homeapp
+        //account2 (linked with role2) can read the box1 (schema = appCellUrl)
+        JsonHttpResponse res = this.callTokenEndpointWithRopcFlow(this.usrCellUrl, "account2", "password2", null, null, null, true);
```
Comment (tochi-y) [inline src/test/java/io/personium/test/jersey/scenario/HomeAppScenarioTest.java]: Better to add status code check.

File: src/test/java/io/personium/test/jersey/scenario/HomeAppScenarioTest.java [hunk 13]
```diff
@@ -0,0 +1,315 @@
...
+        List<NameValuePair> queryList = URLEncodedUtils.parse(location, Charsets.UTF_8);
+        Map<String, String> queryMap = queryList.stream().collect(
+                Collectors.toMap(NameValuePair::getName, NameValuePair::getValue));
+        String grantCode = queryMap.get("code");
+        log.info("GrantCode: " + grantCode);
+
+        // simulate the redirect receiver
+        //  account0 has no role
+        //  account1 has confidential role
+        res = this.callTokenEndpointWithRopcFlow(this.appCellUrl, "account1", "password1", this.usrCellUrl, null, null, false);
```
Comment (tochi-y) [inline src/test/java/io/personium/test/jersey/scenario/HomeAppScenarioTest.java]: Better to add status code check.

File: src/main/java/io/personium/core/PersoniumCoreException.java [hunk 14]
```diff
@@ -1216,4 +1218,45 @@ static int parseCode(String code) {
...
+            l.warn(format, cause);
+            break;
+        case ERROR:
+            l.error(format, cause);
+            break;
+        default:
+            l.error("Exception Severity Not Defined");
+            l.error(format, cause);
+        }
+    	logCauseChain(l, cause);
```
[the remark this answers is not in the document]
Comment (shimono) [reply src/main/java/io/personium/core/PersoniumCoreException.java]: This is intended to log the reasons for the info level errors (400 series HTTP status code)

**Comment by tochi-y** [comment]
@shimono Checkstyle failed and displayed the error message `TreeWalker is not allowed as a parent of SuppressWithNearbyCommentFilter`. The cause is the changes introduced in checkstyle 8.1.

Current pom.xml uses maven-checkstyle-plugin 3.0.0 that use checkstyle 6.18 as default. To be successful, modify following 2 lines to 3.1.0, that use checkstyle 8.19.

- https://github.com/personium/personium-core/blob/cdf9f90d71e8a789e030ce7f3b4097884f74ec84/pom.xml#L427
- https://github.com/personium/personium-core/blob/cdf9f90d71e8a789e030ce7f3b4097884f74ec84/pom.xml#L511

To specify checkstyle version explicitly, modify as following.

```diff
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>3.1.0</version>
+                <dependencies>
+                    <dependency>
+                        <groupId>com.puppycrawl.tools</groupId>
+                        <artifactId>checkstyle</artifactId>
+                        <version>8.26</version>
+                    </dependency>
+                </dependencies>
```
